### ISSUE TITLE
Dark mode logout/login problem

### ISSUE THREAD

**Issue by lost0000** [oatmael/Sneezy#1]
So theres a bit of code in the settings fragment to do with the switch, when switched it changes the layout to dark/light mode then restarts the app. I used start(), stop() because it seemed like the way to go with all the other methods that are involved with restarting the app. Shown below:
https://gyazo.com/f7833fcd53206e7cbaefe6ce13bd9a93

Though it throws this when switched:
https://gyazo.com/3907818bf53931b19b6a78de5d1296a2

Code is here:
https://drive.google.com/file/d/1wfCXIJLc_DGICFIgDjK-n7etIp4SBqTx/view?usp=sharing

Set it so it will switch after restart button hit

**Comment by oatmael** [comment]
Related to app life-cycle issues during the instantiation of the App (which in this case refers to the connection to the database). Because the connection to the database is made during the onStart() part of the life-cycle, restarting the app (onRestart()) will call the connection twice. Due to how the API behaves, attempting to re-instantiate the app object will throw this exception. See below:

![image](https://user-images.githubusercontent.com/45870261/89094303-a6664f00-d401-11ea-8170-2eb0ddf6b4bf.png)

Fixing this bug also created a different bug which would cause the app to logout after restarting, but also not send the user to the login screen (restarting again would put the user there). This was a bug related to issue #2 , which has since been fixed.
