### ISSUE TITLE
Maps behaving differently across different devices

### ISSUE THREAD

**Issue by oatmael** [oatmael/Sneezy#23]
Cause of behavior is unknown, a potential database error?

Google Pixel
![received_427606298202449.png](https://user-images.githubusercontent.com/45870261/93667568-18841780-fac6-11ea-8267-8861e47416a2.png)

OnePlus 8
![Screenshot_20200919-221204.jpg](https://user-images.githubusercontent.com/45870261/93667569-1b7f0800-fac6-11ea-96a7-9bf165a5ea43.jpg)

**Comment by SbrowneA** [comment]
This is most likely due to the different screen dimensions/resolutions but most importantly the aspect ratios. The second Image also looks to be showing a different zoom level (less zoomed in) as it shows a far larger area. The spots seem to be in roughly the same area so I do not believe there is an issue with the database.

![93667569-1b7f0800-fac6-11ea-96a7-9bf165a5ea43](https://user-images.githubusercontent.com/61568703/97278672-faaa8f00-1889-11eb-8ef2-63d5f8d7493e.png)
